### ISSUE TITLE
ValueError: Found array with 0 feature(s) (shape=(2, 0)) while a minimum of 1 is required by MinMaxScaler.

### ISSUE THREAD

**Issue by learnibg** [qiyu3816/MTFNN-CO#3]
How can I resolve this error? It seems that I am unable to locate the dataset that needs to be accessed.

**Comment by qiyu3816** [comment]
MinMaxScaler is only used in utils/dataset.py. If the error is reported in this line, I suggest you check whether the dataset of the input filepath is valid. If you are using the original dataset in this repository but still getting an error, please take detailed screenshots of the code and report.

**Comment by learnibg** [comment]
I have successfully resolved the issue by downloading the raw file from the datasets folder of the MTFNN-CO model and renaming the downloaded .txt file. Thank you very much!

**Comment by qiyu3816** [comment]
OK. Good luck!
